version: '3'

silent: false

tasks:
  init:
    cmds:
      - go mod vendor
  build:
    deps:
      - clean
    cmds:
      - go build -ldflags="-s -w" .
  vet:
    cmds:
      - go vet ./...
  clean:
    cmds:
      - rm -f TP-Link-Router_exporter
      - rm -rf dist
